navbar:
  blog_title: Miao's Blog
  ground_glass:
    enable: true
index:
  banner_img: /images/uploads/wlop.jpeg
  banner_img_height: 100
  slogan:
    text: 这是一个演示博客,可以登陆后台实际测试效果
post:
  banner_img: https://alpha-q3.sourcegcdn.com/2022/08/15/xfuQcQdB.webp
  banner_img_height: 70
  default_index_img: https://alpha-q3.sourcegcdn.com/2022/08/15/mLhMRIoC.webp
archive:
  banner_img: https://api.r10086.com/img-api.php?type=%E6%97%A5%E6%9C%ACCOS%E4%B8%AD%E5%9B%BDCOS
  banner_img_height: 80
  subtitle: null
category:
  banner_img: https://alpha-q3.sourcegcdn.com/2022/08/15/Istxt3oJ.jpg
  banner_img_height: 80
  subtitle: null
tag:
  banner_img: https://alpha-q3.sourcegcdn.com/2022/08/15/758YNXRI.jpg
  banner_img_height: 80
  subtitle: null
about:
  banner_img: https://alpha-q3.sourcegcdn.com/2022/08/15/egQ0Xsru.png
  banner_img_height: 80
  subtitle: null
  avatar: /img/avatar.png
  name: Fluid
  intro: An elegant theme for Hexo
links:
  banner_img: https://alpha-q3.sourcegcdn.com/2022/08/15/sLNBiP2J.jpg
  banner_img_height: 80
  subtitle: null
  items:
    - title: Fluid Repo
      intro: 主题 GitHub 仓库
      link: https://github.com/fluid-dev/hexo-theme-fluid
      avatar: /img/favicon.png
    - title: 暮雨千泷
      intro: 青天白日梦神仙
      link: https://www.myql.xyz
      avatar: https://cdn.jsdelivr.net/gh/leicancun/img@main/images/avatar.webp
